const Alerts = () => {
  return (
    <div className="pt-28 px-6 max-w-6xl mx-auto text-gray-900">
      <h1 className="text-4xl font-bold mb-4">🚨 Automation Alerts</h1>
      <p className="mb-6 text-lg">
        View all automated alerts generated by IMD weather triggers, outbreak risk engine, 
        crop failure prediction, and environmental anomalies.
      </p>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        
        {/* WEATHER ALERTS */}
        <div className="bg-white p-6 rounded-xl shadow-lg">
          <h2 className="text-2xl font-semibold mb-4">🌧 Weather Alerts</h2>
          <p className="text-gray-600">Rainfall, storm warnings, and heatwave notifications.</p>
          <div className="mt-4 p-4 bg-blue-50 rounded-lg text-blue-900">
            No active alerts.
          </div>
        </div>

        {/* CROP ALERTS */}
        <div className="bg-white p-6 rounded-xl shadow-lg">
          <h2 className="text-2xl font-semibold mb-4">🌾 Crop Alerts</h2>
          <p className="text-gray-600">Soil stress, water deficit, and pest conditions.</p>
          <div className="mt-4 p-4 bg-green-50 rounded-lg text-green-900">
            Crop AI running — awaiting latest IMD data…
          </div>
        </div>

        {/* OUTBREAK ALERTS */}
        <div className="bg-white p-6 rounded-xl shadow-lg">
          <h2 className="text-2xl font-semibold mb-4">🦠 Outbreak Alerts</h2>
          <p className="text-gray-600">Based on ICAR disease correlations.</p>
          <div className="mt-4 p-4 bg-red-50 rounded-lg text-red-900">
            No outbreak detected.
          </div>
        </div>

        {/* CUSTOM ALERTS */}
        <div className="bg-white p-6 rounded-xl shadow-lg">
          <h2 className="text-2xl font-semibold mb-4">⚙️ Custom Alerts</h2>
          <p className="text-gray-600">Configure custom alert thresholds.</p>

          <button className="mt-4 bg-purple-600 text-white px-6 py-3 rounded-lg font-bold">
            Create Rule
          </button>
        </div>

      </div>
    </div>
  );
};

export default Alerts;
